### ISSUE TITLE
当持续地向Client::send 发布消息的时候 连接自动断开

### ISSUE THREAD

**Issue by hanhanwink** [walkor/stomp#1]
错误信息
```text
Connection buffer full and close connection
Connection not established
```

**Comment by walkor** [comment]
你发送的速度太快，stomp服务端接收不过来，导致数据积压在内存，积压超过1M就会报这个错误。
你可以通过 Connection::$defaultMaxSendBufferSize 调整缓冲区大小，参见手册 https://www.workerman.net/doc/workerman/tcp-connection/default-max-send-buffer-size.html

**Comment by hanhanwink** [comment]
如果一段时间还是没有达到**Connection::$defaultMaxSendBufferSize**,会有兜底的逻辑去发送缓冲区的数据吗?

**Comment by walkor** [comment]
缓冲的数据超过 Connection::$defaultMaxSendBufferSize 连接会断开，没超过缓冲区的数据会发送给服务端

**Comment by Fluox-Etine** [comment]
> 缓冲的数据超过 Connection::$defaultMaxSendBufferSize 连接会断开，没超过缓冲区的数据会发送给服务端

那如果断开了，会不会重新自动连接啊？？？
