### ISSUE TITLE
need support php8.2

### ISSUE THREAD

**Issue by caylof** [walkor/stomp#5]
tips: Creation of dynamic property Workerman\\Stomp\\Client::$onMessage is deprecated.

may be need property `$onMessage` or the `#[\AllowDynamicProperties]` attribute.

**Comment by walkor** [comment]
done

**Comment by PNixx** [comment]
@walkor `Creation of dynamic property Workerman\Stomp\Exception::$frame is deprecated` in php 8.2

**Comment by walkor** [comment]
Please upgrade to v1.0.9

**Comment by PNixx** [comment]
Thanks for fast fix!
